version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: /agent
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - /docker/server
      - /agent
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - "*"
