docker:
  - changed-files:
      - any-glob-to-any-file:
          - "docker/**"
          - "docker-compose*.yml"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

agent:
  - changed-files:
      - any-glob-to-any-file:
          - "agent/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "*.md"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "pnpm-lock.yaml"
          - "agent/go.mod"
          - "agent/go.sum"
