services:
  vf-agent:
    container_name: vectorflow-agent
    image: ghcr.io/terrifiedbug/vectorflow-agent:${VF_VERSION:-latest}
    env_file:
      - .env
    volumes:
      - agent-data:/var/lib/vf-agent
      - vector-data:/var/lib/vector
    network_mode: host
    restart: unless-stopped

volumes:
  agent-data:
    name: vectorflow-agent-data
  vector-data:
    name: vectorflow-vector-data
