import type { VectorComponentDef } from "../../types";
import {
  tlsSchema,
  batchSchema,
  bufferSchema,
  requestSchema,
  encodingSchema,
  compressionSchema,
  authBasicBearerSchema,
} from "../shared";

export const networkSinks: VectorComponentDef[] = [
  {
    type: "http",
    kind: "sink",
    displayName: "HTTP",
    description: "Send events to an HTTP endpoint",
    category: "Network",
    inputTypes: ["log", "metric", "trace"],
    outputTypes: ["log", "metric", "trace"],
    icon: "Globe",
    configSchema: {
      type: "object",
      properties: {
        uri: {
          type: "string",
          description: "Full HTTP endpoint URI (protocol + host required)",
        },
        method: {
          type: "string",
          enum: ["get", "post", "put", "patch", "delete", "head", "options"],
          description: "HTTP method (default: post)",
        },
        headers: {
          type: "object",
          additionalProperties: { type: "string" },
          description: "Additional HTTP headers (template-enabled)",
        },
        payload_prefix: {
          type: "string",
          description: "JSON prefix for payload body",
        },
        payload_suffix: {
          type: "string",
          description: "JSON suffix for payload body",
        },
        ...authBasicBearerSchema(),
        ...encodingSchema(["json", "ndjson", "text", "logfmt", "csv", "avro", "raw_message"]),
        ...compressionSchema(["none", "gzip", "snappy", "zlib", "zstd"]),
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "10MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["uri"],
    },
  },
  {
    type: "socket",
    kind: "sink",
    displayName: "Socket",
    description: "Send events over a raw TCP or UDP socket",
    category: "Network",
    inputTypes: ["log", "metric"],
    outputTypes: ["log", "metric"],
    icon: "Globe",
    configSchema: {
      type: "object",
      properties: {
        address: {
          type: "string",
          description: "Socket address to connect to (e.g., 127.0.0.1:9000)",
        },
        mode: {
          type: "string",
          enum: ["tcp", "udp", "unix"],
          description: "Socket mode",
        },
        path: {
          type: "string",
          description: "Unix socket path (for unix mode)",
        },
        ...encodingSchema(["json", "text", "raw_message"]),
        ...tlsSchema(),
        ...bufferSchema(),
      },
      required: ["mode"],
    },
  },
  {
    type: "websocket",
    kind: "sink",
    displayName: "WebSocket",
    description: "Send events to a WebSocket server",
    category: "Network",
    status: "beta",
    inputTypes: ["log"],
    outputTypes: ["log"],
    icon: "Globe",
    configSchema: {
      type: "object",
      properties: {
        uri: {
          type: "string",
          description: "WebSocket URI to connect to (ws:// or wss://)",
        },
        ping_interval_secs: {
          type: "number",
          description: "Ping interval in seconds",
        },
        ping_timeout_secs: {
          type: "number",
          description: "Pong timeout in seconds",
        },
        headers: {
          type: "object",
          additionalProperties: { type: "string" },
          description: "Custom headers for the WebSocket handshake",
        },
        ...authBasicBearerSchema(),
        ...encodingSchema(["json", "text", "raw_message"]),
        ...tlsSchema(),
        ...bufferSchema(),
      },
      required: ["uri"],
    },
  },
  {
    type: "websocket_server",
    kind: "sink",
    displayName: "WebSocket Server",
    description: "Serve events to connecting WebSocket clients",
    category: "Network",
    status: "beta",
    inputTypes: ["log"],
    outputTypes: ["log"],
    icon: "Globe",
    configSchema: {
      type: "object",
      properties: {
        address: {
          type: "string",
          description: "Address to listen on (default: 0.0.0.0:9000)",
        },
        ...encodingSchema(["json", "text", "raw_message"]),
        ...tlsSchema(),
        ...bufferSchema(),
      },
      required: [],
    },
  },
  {
    type: "vector",
    kind: "sink",
    displayName: "Vector",
    description: "Send events to another Vector instance",
    category: "Network",
    inputTypes: ["log", "metric", "trace"],
    outputTypes: ["log", "metric", "trace"],
    icon: "Zap",
    configSchema: {
      type: "object",
      properties: {
        address: {
          type: "string",
          description: "Vector destination address (e.g., 127.0.0.1:6000)",
        },
        version: {
          type: "string",
          enum: ["1", "2"],
          description: "Vector protocol version (default: 2)",
        },
        ...compressionSchema(["none", "gzip", "snappy", "zlib", "zstd"]),
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "10MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["address"],
    },
  },
  {
    type: "file",
    kind: "sink",
    displayName: "File",
    description: "Write events to files on disk",
    category: "Local",
    inputTypes: ["log", "metric"],
    outputTypes: ["log", "metric"],
    icon: "FileText",
    configSchema: {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: "File path template (e.g., /tmp/vector-%Y-%m-%d.log)",
        },
        idle_timeout_secs: {
          type: "number",
          description: "Seconds of inactivity before closing a file (default: 30)",
        },
        ...encodingSchema(["json", "ndjson", "text", "csv", "raw_message"]),
        ...compressionSchema(["gzip", "none", "zstd"], "none"),
        ...bufferSchema(),
      },
      required: ["path"],
    },
  },
  {
    type: "blackhole",
    kind: "sink",
    displayName: "Blackhole",
    description: "Discard all events (useful for benchmarks and testing)",
    category: "Debug",
    inputTypes: ["log", "metric", "trace"],
    outputTypes: ["log", "metric", "trace"],
    icon: "Terminal",
    configSchema: {
      type: "object",
      properties: {
        print_interval_secs: {
          type: "number",
          description: "Interval to print throughput stats (0 to disable, default: 1)",
        },
        rate: {
          type: "number",
          description: "Limit events per second (0 = unlimited)",
        },
      },
      required: [],
    },
  },
  {
    type: "console",
    kind: "sink",
    displayName: "Console",
    description: "Print events to stdout for debugging",
    category: "Debug",
    inputTypes: ["log", "metric", "trace"],
    outputTypes: ["log", "metric", "trace"],
    icon: "Terminal",
    configSchema: {
      type: "object",
      properties: {
        ...encodingSchema(["json", "text", "logfmt"]),
      },
      required: [],
    },
  },
  {
    type: "webhdfs",
    kind: "sink",
    displayName: "WebHDFS",
    description: "Write events to HDFS via WebHDFS REST API",
    category: "Network",
    status: "beta",
    inputTypes: ["log"],
    outputTypes: ["log"],
    icon: "Database",
    configSchema: {
      type: "object",
      properties: {
        endpoint: {
          type: "string",
          description: "WebHDFS namenode endpoint (e.g., http://namenode:9870)",
        },
        prefix: {
          type: "string",
          description: "HDFS path prefix template",
        },
        user: {
          type: "string",
          description: "HDFS user name",
        },
        ...encodingSchema(["json", "ndjson", "text", "csv", "raw_message"]),
        ...compressionSchema(["gzip", "none", "zstd"], "none"),
        ...batchSchema({ max_bytes: "10MB", timeout_secs: "300" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["endpoint", "prefix"],
    },
  },
];
