import type { VectorComponentDef } from "../../types";
import {
  tlsSchema,
  batchSchema,
  bufferSchema,
  requestSchema,
  encodingSchema,
  compressionSchema,
  authBasicBearerSchema,
} from "../shared";

export const networkSinks: VectorComponentDef[] = [
  {
    type: "http",
    kind: "sink",
    displayName: "HTTP",
    description: "Send events to an HTTP endpoint",
    category: "Network",
    inputTypes: ["log", "metric", "trace"],
    outputTypes: ["log", "metric", "trace"],
    icon: "Globe",
    configSchema: {
      type: "object",
      properties: {
        uri: {
          type: "string",
          description: "Full HTTP endpoint URI (protocol + host required)",
        },
        method: {
          type: "string",
          enum: ["get", "post", "put", "patch", "delete", "head", "options"],
          description: "HTTP method",
          default: "post",
        },
        payload_prefix: {
          type: "string",
          description: "JSON prefix for payload body",
        },
        payload_suffix: {
          type: "string",
          description: "JSON suffix for payload body",
        },
        ...authBasicBearerSchema(),
        ...encodingSchema([
          "json",
          "ndjson",
          "text",
          "logfmt",
          "csv",
          "avro",
          "raw_message",
          "native",
          "native_json",
          "gelf",
          "cef",
          "syslog",
          "otlp",
          "protobuf",
        ]),
        ...compressionSchema(["none", "gzip", "snappy", "zlib", "zstd"]),
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "10MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["uri", "encoding"],
    },
  },
  {
    type: "socket",
    kind: "sink",
    displayName: "Socket",
    description: "Send events over a raw TCP or UDP socket",
    category: "Network",
    inputTypes: ["log", "metric"],
    outputTypes: ["log", "metric"],
    icon: "Globe",
    configSchema: {
      type: "object",
      properties: {
        address: {
          type: "string",
          description:
            "Socket address to connect to (e.g., 92.12.333.224:5000). Required for tcp and udp modes.",
          dependsOn: { field: "mode", value: ["tcp", "udp"] },
        },
        mode: {
          type: "string",
          enum: ["tcp", "udp", "unix_datagram", "unix_stream"],
          description: "The type of socket to use",
        },
        path: {
          type: "string",
          description:
            "Unix socket path (absolute path, required for unix_stream and unix_datagram modes)",
          dependsOn: { field: "mode", value: ["unix_datagram", "unix_stream"] },
        },
        send_buffer_bytes: {
          type: "number",
          description:
            "Configures the send buffer size (SO_SNDBUF) for the socket. Relevant for tcp and udp modes.",
          dependsOn: { field: "mode", value: ["tcp", "udp"] },
        },
        ...encodingSchema([
          "json",
          "text",
          "raw_message",
          "ndjson",
          "logfmt",
          "csv",
          "avro",
          "native",
          "native_json",
          "gelf",
          "cef",
          "syslog",
          "otlp",
          "protobuf",
        ]),
        ...tlsSchema(),
        ...bufferSchema(),
      },
      required: ["mode", "encoding"],
    },
  },
  {
    type: "websocket",
    kind: "sink",
    displayName: "WebSocket",
    description: "Send events to a WebSocket server",
    category: "Network",
    status: "beta",
    inputTypes: ["log"],
    outputTypes: ["log"],
    icon: "Globe",
    configSchema: {
      type: "object",
      properties: {
        uri: {
          type: "string",
          description: "WebSocket URI to connect to (ws:// or wss://)",
        },
        ping_interval: {
          type: "number",
          description:
            "Interval in seconds for sending Ping frames to remote peer. If unset, pings are not sent automatically.",
        },
        ping_timeout: {
          type: "number",
          description:
            "Maximum wait time in seconds for Pong responses. Connection re-establishes on timeout. Ignored unless ping_interval is set.",
        },
        ...authBasicBearerSchema(),
        ...encodingSchema([
          "json",
          "text",
          "raw_message",
          "ndjson",
          "logfmt",
          "csv",
          "avro",
          "native",
          "native_json",
          "gelf",
          "cef",
          "syslog",
          "otlp",
          "protobuf",
        ]),
        ...tlsSchema(),
        ...bufferSchema(),
      },
      required: ["uri", "encoding"],
    },
  },
  {
    type: "websocket_server",
    kind: "sink",
    displayName: "WebSocket Server",
    description: "Serve events to connecting WebSocket clients",
    category: "Network",
    status: "beta",
    inputTypes: ["log"],
    outputTypes: ["log"],
    icon: "Globe",
    configSchema: {
      type: "object",
      properties: {
        address: {
          type: "string",
          description: "Address to listen on (must include port, e.g., 0.0.0.0:80)",
        },
        ...encodingSchema([
          "json",
          "text",
          "raw_message",
          "ndjson",
          "logfmt",
          "csv",
          "avro",
          "native",
          "native_json",
          "gelf",
          "cef",
          "syslog",
          "otlp",
          "protobuf",
        ]),
        ...tlsSchema(),
        ...bufferSchema(),
      },
      required: ["address", "encoding"],
    },
  },
  {
    type: "vector",
    kind: "sink",
    displayName: "Vector",
    description: "Send events to another Vector instance",
    category: "Network",
    inputTypes: ["log", "metric", "trace"],
    outputTypes: ["log", "metric", "trace"],
    icon: "Zap",
    configSchema: {
      type: "object",
      properties: {
        address: {
          type: "string",
          description:
            "The downstream Vector address to connect to (must include port, e.g., 127.0.0.1:6000)",
        },
        compression: {
          type: "boolean",
          description: "Enable gzip compression for data sent to the downstream Vector instance",
          default: false,
        },
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "10MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["address"],
    },
  },
  {
    type: "file",
    kind: "sink",
    displayName: "File",
    description: "Write events to files on disk",
    category: "Local",
    inputTypes: ["log", "metric"],
    outputTypes: ["log", "metric"],
    icon: "FileText",
    configSchema: {
      type: "object",
      properties: {
        path: {
          type: "string",
          description:
            "File path template (e.g., /tmp/vector-%Y-%m-%d.log). Compression format extension must be explicit.",
        },
        idle_timeout_secs: {
          type: "number",
          description: "Seconds of inactivity before flushing and closing a file",
          default: 30,
        },
        ...encodingSchema([
          "json",
          "ndjson",
          "text",
          "csv",
          "raw_message",
          "logfmt",
          "avro",
          "native",
          "native_json",
          "gelf",
          "cef",
          "syslog",
          "otlp",
          "protobuf",
        ]),
        ...compressionSchema(["gzip", "none", "zstd"], "none"),
        ...bufferSchema(),
      },
      required: ["path", "encoding"],
    },
  },
  {
    type: "blackhole",
    kind: "sink",
    displayName: "Blackhole",
    description: "Discard all events (useful for benchmarks and testing)",
    category: "Debug",
    inputTypes: ["log", "metric", "trace"],
    outputTypes: ["log", "metric", "trace"],
    icon: "Terminal",
    configSchema: {
      type: "object",
      properties: {
        print_interval_secs: {
          type: "number",
          description:
            "The interval between reporting a summary of activity (0 to disable)",
          default: 0,
        },
        rate: {
          type: "number",
          description:
            "Maximum events per second the sink can consume (default: unlimited)",
        },
      },
      required: [],
    },
  },
  {
    type: "console",
    kind: "sink",
    displayName: "Console",
    description: "Print events to stdout for debugging",
    category: "Debug",
    inputTypes: ["log", "metric", "trace"],
    outputTypes: ["log", "metric", "trace"],
    icon: "Terminal",
    configSchema: {
      type: "object",
      properties: {
        target: {
          type: "string",
          enum: ["stdout", "stderr"],
          description: "The standard stream to write to",
          default: "stdout",
        },
        ...encodingSchema([
          "json",
          "text",
          "logfmt",
          "csv",
          "avro",
          "raw_message",
          "native",
          "native_json",
          "gelf",
          "cef",
          "syslog",
          "otlp",
          "protobuf",
        ]),
        ...bufferSchema(),
      },
      required: ["encoding"],
    },
  },
  {
    type: "webhdfs",
    kind: "sink",
    displayName: "WebHDFS",
    description: "Write events to HDFS via WebHDFS REST API",
    category: "Network",
    status: "beta",
    inputTypes: ["log"],
    outputTypes: ["log"],
    icon: "Database",
    configSchema: {
      type: "object",
      properties: {
        endpoint: {
          type: "string",
          description:
            "WebHDFS namenode endpoint (e.g., http://127.0.0.1:9870)",
        },
        root: {
          type: "string",
          description:
            "Base directory path for WebHDFS. Final file path follows format: {root}/{prefix}{suffix}.",
        },
        prefix: {
          type: "string",
          description:
            "Directory prefix for organizing stored objects (template-enabled, should end with /)",
        },
        ...encodingSchema([
          "json",
          "ndjson",
          "text",
          "csv",
          "raw_message",
          "logfmt",
          "avro",
          "native",
          "native_json",
          "gelf",
          "cef",
          "syslog",
          "otlp",
          "protobuf",
        ]),
        ...compressionSchema(["gzip", "none", "snappy", "zlib", "zstd"], "gzip"),
        ...batchSchema({ max_bytes: "10MB", timeout_secs: "300" }),
        ...bufferSchema(),
      },
      required: ["endpoint", "prefix", "encoding"],
    },
  },
];
