import type { VectorComponentDef } from "../../types";
import {
  tlsSchema,
  batchSchema,
  bufferSchema,
  requestSchema,
  encodingSchema,
  compressionSchema,
  authBasicBearerSchema,
} from "../shared";

export const observabilitySinks: VectorComponentDef[] = [
  {
    type: "new_relic",
    kind: "sink",
    displayName: "New Relic",
    description: "Send logs, metrics, or events to New Relic",
    category: "Observability",
    inputTypes: ["log", "metric"],
    outputTypes: ["log", "metric"],
    icon: "Send",
    configSchema: {
      type: "object",
      properties: {
        license_key: {
          type: "string",
          description: "New Relic license key",
          sensitive: true,
        },
        account_id: {
          type: "string",
          description: "New Relic account ID",
        },
        api: {
          type: "string",
          enum: ["logs", "metrics", "events"],
          description: "New Relic API to use (default: logs)",
        },
        region: {
          type: "string",
          enum: ["us", "eu"],
          description: "New Relic region (default: us)",
        },
        ...compressionSchema(["gzip", "none"], "gzip"),
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "1MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["license_key"],
    },
  },
  {
    type: "honeycomb",
    kind: "sink",
    displayName: "Honeycomb",
    description: "Send log events to Honeycomb.io",
    category: "Observability",
    inputTypes: ["log"],
    outputTypes: ["log"],
    icon: "Send",
    configSchema: {
      type: "object",
      properties: {
        api_key: {
          type: "string",
          description: "Honeycomb API key",
          sensitive: true,
        },
        dataset: {
          type: "string",
          description: "Honeycomb dataset name",
        },
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "5MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["api_key", "dataset"],
    },
  },
  {
    type: "axiom",
    kind: "sink",
    displayName: "Axiom",
    description: "Send log events to Axiom",
    category: "Observability",
    inputTypes: ["log"],
    outputTypes: ["log"],
    icon: "Send",
    configSchema: {
      type: "object",
      properties: {
        token: {
          type: "string",
          description: "Axiom API token",
          sensitive: true,
        },
        dataset: {
          type: "string",
          description: "Axiom dataset name",
        },
        org_id: {
          type: "string",
          description: "Axiom organization ID",
        },
        url: {
          type: "string",
          description: "Axiom API URL (default: https://api.axiom.co)",
        },
        ...compressionSchema(["gzip", "none", "zstd"], "gzip"),
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "10MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["token", "dataset"],
    },
  },
  {
    type: "appsignal",
    kind: "sink",
    displayName: "AppSignal",
    description: "Send logs and metrics to AppSignal",
    category: "Observability",
    inputTypes: ["log", "metric"],
    outputTypes: ["log", "metric"],
    icon: "Send",
    configSchema: {
      type: "object",
      properties: {
        push_api_key: {
          type: "string",
          description: "AppSignal push API key",
          sensitive: true,
        },
        endpoint: {
          type: "string",
          description: "AppSignal API endpoint (default: https://appsignal-endpoint.net)",
        },
        ...compressionSchema(["gzip", "none"], "gzip"),
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "5MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["push_api_key"],
    },
  },
  {
    type: "mezmo",
    kind: "sink",
    displayName: "Mezmo",
    description: "Send log events to Mezmo (formerly LogDNA)",
    category: "Observability",
    inputTypes: ["log"],
    outputTypes: ["log"],
    icon: "Send",
    configSchema: {
      type: "object",
      properties: {
        api_key: {
          type: "string",
          description: "Mezmo ingestion API key",
          sensitive: true,
        },
        hostname: {
          type: "string",
          description: "Hostname to attach to events",
        },
        mac: {
          type: "string",
          description: "MAC address to attach to events",
        },
        ip: {
          type: "string",
          description: "IP address to attach to events",
        },
        tags: {
          type: "array",
          items: { type: "string" },
          description: "Tags to attach to events",
        },
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "10MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["api_key"],
    },
  },
  {
    type: "sematext_logs",
    kind: "sink",
    displayName: "Sematext Logs",
    description: "Send log events to Sematext Cloud",
    category: "Observability",
    inputTypes: ["log"],
    outputTypes: ["log"],
    icon: "Send",
    configSchema: {
      type: "object",
      properties: {
        token: {
          type: "string",
          description: "Sematext application token",
          sensitive: true,
        },
        region: {
          type: "string",
          enum: ["us", "eu"],
          description: "Sematext region (default: us)",
        },
        endpoint: {
          type: "string",
          description: "Custom Sematext endpoint URL",
        },
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "10MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["token"],
    },
  },
  {
    type: "sematext_metrics",
    kind: "sink",
    displayName: "Sematext Metrics",
    description: "Send metric events to Sematext Cloud",
    category: "Observability",
    inputTypes: ["metric"],
    outputTypes: ["metric"],
    icon: "Send",
    configSchema: {
      type: "object",
      properties: {
        token: {
          type: "string",
          description: "Sematext application token",
          sensitive: true,
        },
        region: {
          type: "string",
          enum: ["us", "eu"],
          description: "Sematext region (default: us)",
        },
        default_namespace: {
          type: "string",
          description: "Default metric namespace",
        },
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "10MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["token"],
    },
  },
  {
    type: "humio_logs",
    kind: "sink",
    displayName: "Humio Logs",
    description: "Send log events to Humio (CrowdStrike Falcon LogScale)",
    category: "Observability",
    inputTypes: ["log"],
    outputTypes: ["log"],
    icon: "Send",
    configSchema: {
      type: "object",
      properties: {
        token: {
          type: "string",
          description: "Humio ingest token",
          sensitive: true,
        },
        endpoint: {
          type: "string",
          description: "Humio endpoint URL (default: https://cloud.humio.com)",
        },
        source: {
          type: "string",
          description: "Event source value (template-enabled)",
        },
        event_type: {
          type: "string",
          description: "Event type (template-enabled)",
        },
        host_key: {
          type: "string",
          description: "Field for the host value",
        },
        ...encodingSchema(["json", "text"]),
        ...compressionSchema(["gzip", "none"], "gzip"),
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "1MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["token"],
    },
  },
  {
    type: "humio_metrics",
    kind: "sink",
    displayName: "Humio Metrics",
    description: "Send metric events to Humio (CrowdStrike Falcon LogScale)",
    category: "Observability",
    inputTypes: ["metric"],
    outputTypes: ["metric"],
    icon: "Send",
    configSchema: {
      type: "object",
      properties: {
        token: {
          type: "string",
          description: "Humio ingest token",
          sensitive: true,
        },
        endpoint: {
          type: "string",
          description: "Humio endpoint URL (default: https://cloud.humio.com)",
        },
        source: {
          type: "string",
          description: "Event source value (template-enabled)",
        },
        host_key: {
          type: "string",
          description: "Field for the host value",
        },
        ...compressionSchema(["gzip", "none"], "gzip"),
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "1MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["token"],
    },
  },
  {
    type: "keep",
    kind: "sink",
    displayName: "Keep",
    description: "Send alert events to Keep AIOps platform",
    category: "Observability",
    status: "beta",
    inputTypes: ["log"],
    outputTypes: ["log"],
    icon: "Send",
    configSchema: {
      type: "object",
      properties: {
        api_key: {
          type: "string",
          description: "Keep API key",
          sensitive: true,
        },
        endpoint: {
          type: "string",
          description: "Keep API endpoint URL",
        },
        ...tlsSchema(),
        ...batchSchema({ max_bytes: "5MB", timeout_secs: "1" }),
        ...bufferSchema(),
        ...requestSchema(),
      },
      required: ["api_key", "endpoint"],
    },
  },
];
