-- UX-6: persist the desired config checksum per pipeline.
--
-- The agent config endpoint computes a checksum (config YAML + resolved secrets)
-- each time it serves a pipeline's config; it was only cached process-locally, so
-- config-drift detection broke across restarts and HA replicas (a report served
-- by an instance that never served that pipeline's config saw no desired value
-- and reported "unknown"). Persisting it makes drift detection correct and keeps
-- the fleet KPI and the config-drift report consistent across replicas.
--
-- Additive, nullable column on an already-RLS-protected table — no policy or
-- backfill needed (it self-populates on the next agent config poll).
ALTER TABLE "Pipeline" ADD COLUMN "desiredConfigChecksum" TEXT;
